### ISSUE TITLE
CE3 Documentation Mega-TODO List

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1715]
It's a little easier to consolidate these things into one place. Structuring things based on the sidebar:

- **Overview**
  + [ ] Need a beginner-friendly explainer of what `IO` *is*
  + [ ] Performance page touching on some top-line general numbers and concepts
  + [ ] Tracing documentation
- [x] **Getting Started** (this whole section should probably just be ported from CE2's microsite, because the walkthrough and topic is good)
- [ ] **Best Practices** (this should be a section covering best practices on how to structure your applications, ways to solve certain problems like dependency injection, etc; general "leveling up" stuff)
- **Standard Library**
  + [ ] `Console`
  + [ ] `Random`
  + [ ] Some of the articles in this section also need a bit of cleanup for consistency
- [ ] **Ecosystem** (I'm envisioning this as a use-case focused section with entries for "Http" (subsections "Client" and "Server"), "Kafka", etc; mostly just linking to external libraries and maybe giving a quickly copy/pasteable snippet for sbt and call-site)
- [ ] **Scaling and Tuning** (advice for how you run Cats Effect-powered services at scale and what it means to tune them for high load)

**Comment by vasilmkd** [comment]
I volunteer to do the performance page

**Comment by yatesco** [comment]
I volunteer to _read_ the dependency injection page as I am not even in a kitten in this ecosystem yet (but I do know a bunch about DI ;-))

**Comment by aluscent** [comment]
Still working on this issue? Which part?
I might be of help.

**Comment by najuna-brian** [comment]
I completed the comprehensive CE3 documentation as outlined in this issue! 

Happy to make any adjustments based on feedback.
Thank you 😊 

_Later **closed** to open Separate PRs for each Change as guided_ by @ybasket
