### ISSUE TITLE
Cats Effect 3.3.0 release checklist

### ISSUE THREAD

**Issue by vasilmkd** [typelevel/cats-effect#2567]
Things to complete before the release:

- [x] Merge `series/3.2.x` into `series/3.x` to get all the documentation changes from that branch.
- [ ] Release.
- [ ] Create a `series/3.3.x` branch.
- [ ] Switch the Cats Effect 3 documentation git submodule in `docs` to `series/3.x.`.
- [x] https://github.com/typelevel/cats-effect/issues/2569

**Comment by djspiewak** [comment]
IMO we don't need the `series/3.3.x` branch just yet. We can create that lazily when we have to make a change that moves us into 3.4.x territory.
